services:
  # auth-api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: auth-api-app
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
  #     REDIS_HOST: ${REDIS_HOST}
  #     REDIS_PORT: ${REDIS_PORT}
  #     REDIS_COMMON_HOST=${REDIS_COMMON_HOST}
  #     REDIS_COMMON_PORT=${REDIS_COMMON_PORT}
  #     MAIL_USER: ${MAIL_USER}
  #     MAIL_PASSWORD: ${MAIL_PASSWORD}
  #     MAIL_HOST: ${MAIL_HOST}
  #     MAIL_PORT: ${MAIL_PORT}
  #     JWT_SECRET: ${JWT_SECRET}
  #     FRONTEND_URL: ${FRONTEND_URL}
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy

  postgres:
    image: postgres:18
    container_name: auth-api-postgres
    restart: always
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 2s
      timeout: 5s
      retries: 10

  redis:
    image: redis:8.2.2
    container_name: auth-api-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 10

  common-redis:
    image: redis:8.2.2
    container_name: common-redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - common_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 10

volumes:
  postgres_data:
  redis_data:
  common_data: